version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes: 
      - ./.data:/data/db
    ports: 
      - 27017:27017
  front-end:
    image: node
    build:
      context: ./front/
    volumes:
      - ./front:/app
    ports:
      - 4000:4000